### ISSUE TITLE
HideUI 1.0.3 has incorrect file structure

### ISSUE THREAD

**Issue by torkus** [Estasleyendoesto/HideUI#1]
I noticed in [HideUI 1.0.3](https://github.com/Estasleyendoesto/HideUI/releases/tag/HideUI-1.0.3) that the `HideUI` folder is now nested within a folder called `HideUI-1.0.3`.

`HideUI-1.0.2` is fine.

**Comment by Estasleyendoesto** [comment]
Thanks for the warning; it has been corrected.
